---



- name: Copy redis configuration
  template:
    src: etc-redis.conf.j2
    dest: /etc/redis.conf
    owner: root
    group: root
    mode: 0644
  notify: restart redis
  tags:
    - redis
    - redis-config


- name: Allow VM overcommit
  sysctl:
    name: vm.overcommit_memory
    value: 1
    state: present
    reload: yes
    ignoreerrors: yes
  tags:
    - redis
    - redis-config

- name: Raise max open files for redis
  template:
    src: 91-redis.conf.j2
    dest: /etc/security/limits.d/91-redis.conf
    backup: yes
    owner: root
    group: root
    mode: 0644
  notify: restart redis
  tags:
    - redis
    - redis-config

- name: Create ulimit config file for redis
  template:
    src: etc-sysconfig-redis.j2
    dest: /etc/sysconfig/redis
    backup: yes
    owner: root
    group: root
    mode: 0644
  notify: restart redis
  tags:
    - redis
    - redis-config

- name: Allow redis to bind to non-default port
  seport:
    context: redis_port_t
    port: "{{ redis_port }}"
    protocol: tcp
    state: present
  when: redis_port != 6379
  notify: restart redis
  tags:
    - redis
    - redis-config
    - redis-selinux

