---


- name: "Copy RPM"
  become: yes
  copy:
    src: "{{ redis_download_path }}/{{ redis_rpm }}.rpm"
    dest: "/tmp/{{ redis_rpm }}.rpm"

- name: Install the Redis rpm from local rpm
  yum:
    name: "/tmp/{{ redis_rpm }}.rpm"
    state: present


- name: Get redis version
  command: redis-cli -p {{ redis_port }} --version
  register: redis_version_check
  changed_when: False
  tags:
    - redis
    - redis-version
    - redis-selinux
    - redis-config


- name: Set redis_version
  set_fact:
    redis_version: "{{ redis_version_check.stdout.split()[1][:3] }}"
  tags:
    - redis
    - redis-version
    - redis-selinux
    - redis-config