---


- include: set-role-variables.yml

- include: install.yml

- include: config.yml


- name: Start and enable redis
  service:
    name: redis
    enabled: yes
    state: started
  tags:
    - redis

