---
# file: tasks/set-role-variables.yml
# set necessary role variables.
#

- name: compose url for downloading file, if necessary
  set_fact:
    redis_rpm: "redis-{{ redis_version }}-1.el7.remi.x86_64"
    
- name: compose url for downloading file, if necessary
  set_fact:
    redis_rpm_url:  "{{ redis_download_base_url }}/{{ redis_rpm }}.rpm"

