---
# file: tasks/set-role-variables.yml
# set necessary role variables.
#

- name: compose url for downloading file, if necessary
  set_fact:
    redis_tarball: redis-{{ redis.version }}
- name: compose url for downloading file, if necessary
  set_fact:
    redis_tarball_url:  "{{ redis.download_base_url }}/{{ redis_tarball }}.tar.gz"

